Save Format v3.0(19990112)
@begin Projects
 0 "1&p_stars&STARS.PBL";
@end;
appname "stars";
applib "stars.pbl";
LibList "STARS.PBL;APPMGR.PBL;FUNC.PBL;DW2XLS.PBL;QUERY.PBL;PATTRN.PBL;SUBSET.PBL;CASE.PBL;RATIO.PBL;RNDSMP.PBL;SUMMRY.PBL;NORM.PBL;PROVPAT.PBL;FILTER.PBL;CODE.PBL;DICT.PBL;PERIOD.PBL;BASE.PBL;PDR.PBL;CATEG.PBL;CLAIMS.PBL;MAP.PBL;NOTES.PBL;RSTR.PBL;TARGET.PBL;USER.PBL;appeon_workarounds.pbl";
type "pb";
